# 1.1.1.0
# created: 08 May 2022
# updated: 01 Oct 2022
# update checkout to v3.0.2
# Checks .cfg files for syntax errors
# https://github.com/KSP-CKAN/KSPMMCfgParser

name: Config file validation
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  validate:
    name: Validate cfg files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        # uses: actions/checkout@lastest
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 1
      - name: Validate config files
        uses: KSP-CKAN/KSPMMCfgParser@master